variable "region" {}
variable "project_modules" {}
variable "vpc_cidr" {}
variable "public_subnet_az1_cidr" {}
variable "public_subnet_az2_cidr" {}
variable "private_app_subnet_az1_cidr" {}
variable "private_app_subnet_az2_cidr" {}
variable "private_database_subnet_az1_cidr" {}
variable "private_database_subnet_az2_cidr" {}